apiVersion: v1
kind: Service
metadata:
  name: wsk-svc
  namespace: staging
spec:
  selector:
    app: wsk-base
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 30
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  #     nodePort: 30000
  # type: NodePort
