apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsk-deploy
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wsk-base
  template:
    metadata:
      labels:
        app: wsk-base
        track: stable
        version: 0.1.1
    spec:
      containers:
        - name: websocket-base
          image: riskiwah/websock-example:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: "redis-master.staging"
          ports:
            - name: websocket
              containerPort: 5000
